/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CredentialDirectory;
import model.MainSystem;
import model.City;
import UI.MainJFrame;
import java.awt.Window;
import java.util.ArrayList;
import javax.swing.SwingUtilities;
import model.Community;
import model.House;
import model.Crudops;
import model.Hospital;
/**
 *
 * @author abhis
 */
public class CityAdminCreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CityAdminCreateJPanel
     */
    City city1;
    Crudops crudops1;
    MainSystem mainSystem;
    CredentialDirectory allcredentials;
    public CityAdminCreateJPanel(MainSystem mainSystem,CredentialDirectory allcredentials) {
        initComponents();
        this.crudops1 = crudops1;
        this.allcredentials = allcredentials;
        //this.city1 = city1;
        this.mainSystem = mainSystem;
        
        try{
        
            popcomm();
            popcity();
            popcity1();
        }
        catch(Exception e){
            System.out.println("CHILL ");
        }
        
        
        try{
            if(allcredentials.getCredential().get(allcredentials.getCredential().size()-1).getRole().equals("Community Admin")){
                System.out.println("COMMUNITY ADMIN HAS LOGGED IN");
                btncreate.setVisible(false);
            }
        }
        catch(Exception e){
            System.out.println("CHILL ");
            //JOptionPane.showMessageDialog(this, "Modify Communities");
        }

                
    }
    public void setLabelText() {
        jLabel1.setText("Welcome Community Admin");
    }
    
    public boolean rolecheck(){
        MainJFrame mj = new MainJFrame();
        String password;
        String username;
        String role;
        password = "fd2556b9dd";
        username = "admin";
        role = mj.getrole();
        boolean b1 =  allcredentials.checkSysAdminCred(username, password, role);
        
        return b1;
    }

    public boolean IdCheck(int id){
        boolean b1 = false;
        //city
        ArrayList<City> idcheck = mainSystem.searchCity(txtCity.getText());
        if(idcheck.contains(Integer.valueOf(id))){
            return false;
        }else{
            return true;
        }
    }    
        
        
//        if(role.equals("city")){
//          System.out.println("IN CITY");  
//          for(City ct : mainSystem.getAllcities()){
//              
//              if(ct.getCityId() == id){
//                  b1 = false;
//                  System.out.println("SAME ID");                    
//              }
//              else{
//                  b1 = true;
//              }
//                   
//          }
//      }
//      //Community  
//      if(role.equals("Community")){
//          for(City ct : mainSystem.getAllcities()){
//              for(Community com : ct.getAllcommunities()){
//                  if(com.getZipcode()==id){
//                      b1 = false; 
//                  }
//                  else{
//                      b1 = true;
//                  }
//              }
//          }
//      }
//      
//      if(role.equals("House")){
//          for(City ct : mainSystem.getAllcities()){
//              for(Community com : ct.getAllcommunities()){
//                  for(House hse : com.getAllhouses()){
//                      if(com.getCommunityname().equals(hse.getCommunity().getCommunityname())){
//                          if(hse.getHouseno()==id){
//                              b1 = false; 
//                          }else{
//                              b1 = true;
//                          }
//                      }
//                  }
//              }
//          }          
//      }
//      
//      return b1;  
//}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblCityid = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        lblCommunityid = new javax.swing.JLabel();
        lblHouse = new javax.swing.JLabel();
        lblHouseNo = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtCityid = new javax.swing.JTextField();
        txtCommunity = new javax.swing.JTextField();
        txtCommunityid = new javax.swing.JTextField();
        txtHouse = new javax.swing.JTextField();
        txtHouseno = new javax.swing.JTextField();
        btncreate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecords = new javax.swing.JTable();
        lblHouseNo1 = new javax.swing.JLabel();
        txtHouseno1 = new javax.swing.JTextField();
        txtHouse1 = new javax.swing.JTextField();
        lblHouse1 = new javax.swing.JLabel();
        lblCommunity1 = new javax.swing.JLabel();
        txtCommunity1 = new javax.swing.JTextField();
        txtCommunityid1 = new javax.swing.JTextField();
        lblCommunityid1 = new javax.swing.JLabel();
        txtCity1 = new javax.swing.JTextField();
        lblCity1 = new javax.swing.JLabel();
        txtCityid1 = new javax.swing.JTextField();
        lblCityid1 = new javax.swing.JLabel();
        btnedit = new javax.swing.JButton();
        btnview = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnpop = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRecords1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRecords2 = new javax.swing.JTable();
        btncreate1 = new javax.swing.JButton();
        btncreate2 = new javax.swing.JButton();
        btnview1 = new javax.swing.JButton();
        btnpop1 = new javax.swing.JButton();
        btndelete1 = new javax.swing.JButton();
        btnpop2 = new javax.swing.JButton();
        btndelete2 = new javax.swing.JButton();
        btnview2 = new javax.swing.JButton();
        btnedit1 = new javax.swing.JButton();
        btnedit2 = new javax.swing.JButton();
        ComboBoxCity = new javax.swing.JComboBox<>();
        lblCommunity2 = new javax.swing.JLabel();
        ComboBoxCity1 = new javax.swing.JComboBox<>();
        lblCommunity3 = new javax.swing.JLabel();
        ComboBoxComm = new javax.swing.JComboBox<>();
        lblCommunity4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setForeground(new java.awt.Color(153, 255, 51));
        setToolTipText("");
        setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Community");

        lblCity.setText("City ");

        lblCityid.setText("CityID");

        lblCommunity.setText("Community");

        lblCommunityid.setText("CommunityID");

        lblHouse.setText("House");

        lblHouseNo.setText("House Number");

        txtCityid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCityidKeyTyped(evt);
            }
        });

        txtCommunityid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCommunityidKeyTyped(evt);
            }
        });

        txtHouseno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHousenoKeyTyped(evt);
            }
        });

        btncreate.setBackground(new java.awt.Color(0, 0, 0));
        btncreate.setForeground(new java.awt.Color(255, 255, 255));
        btncreate.setText("Create");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });

        tblRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "City", "CityId"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRecords);

        lblHouseNo1.setText("House Number");

        txtHouseno1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHouseno1KeyTyped(evt);
            }
        });

        lblHouse1.setText("House");

        lblCommunity1.setText("Community");

        txtCommunityid1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCommunityid1KeyTyped(evt);
            }
        });

        lblCommunityid1.setText("CommunityID");

        lblCity1.setText("City ");

        txtCityid1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCityid1KeyTyped(evt);
            }
        });

        lblCityid1.setText("CityID");

        btnedit.setBackground(new java.awt.Color(0, 0, 0));
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnview.setBackground(new java.awt.Color(0, 0, 0));
        btnview.setForeground(new java.awt.Color(255, 255, 255));
        btnview.setText("View");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(0, 0, 0));
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnpop.setBackground(new java.awt.Color(0, 0, 0));
        btnpop.setForeground(new java.awt.Color(255, 255, 255));
        btnpop.setText("Populate table");
        btnpop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpopActionPerformed(evt);
            }
        });

        tblRecords1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "House", "HouseId", "Community", "City"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRecords1);

        tblRecords2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Community", "CommunityId", "City"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblRecords2);

        btncreate1.setBackground(new java.awt.Color(0, 0, 0));
        btncreate1.setForeground(new java.awt.Color(255, 255, 255));
        btncreate1.setText("Create");
        btncreate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreate1ActionPerformed(evt);
            }
        });

        btncreate2.setBackground(new java.awt.Color(0, 0, 0));
        btncreate2.setForeground(new java.awt.Color(255, 255, 255));
        btncreate2.setText("Create");
        btncreate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreate2ActionPerformed(evt);
            }
        });

        btnview1.setBackground(new java.awt.Color(0, 0, 0));
        btnview1.setForeground(new java.awt.Color(255, 255, 255));
        btnview1.setText("View");
        btnview1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnview1ActionPerformed(evt);
            }
        });

        btnpop1.setBackground(new java.awt.Color(0, 0, 0));
        btnpop1.setForeground(new java.awt.Color(255, 255, 255));
        btnpop1.setText("Populate table");
        btnpop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpop1ActionPerformed(evt);
            }
        });

        btndelete1.setBackground(new java.awt.Color(0, 0, 0));
        btndelete1.setForeground(new java.awt.Color(255, 255, 255));
        btndelete1.setText("Delete");
        btndelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete1ActionPerformed(evt);
            }
        });

        btnpop2.setBackground(new java.awt.Color(0, 0, 0));
        btnpop2.setForeground(new java.awt.Color(255, 255, 255));
        btnpop2.setText("Populate table");
        btnpop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpop2ActionPerformed(evt);
            }
        });

        btndelete2.setBackground(new java.awt.Color(0, 0, 0));
        btndelete2.setForeground(new java.awt.Color(255, 255, 255));
        btndelete2.setText("Delete");
        btndelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete2ActionPerformed(evt);
            }
        });

        btnview2.setBackground(new java.awt.Color(0, 0, 0));
        btnview2.setForeground(new java.awt.Color(255, 255, 255));
        btnview2.setText("View");
        btnview2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnview2ActionPerformed(evt);
            }
        });

        btnedit1.setBackground(new java.awt.Color(0, 0, 0));
        btnedit1.setForeground(new java.awt.Color(255, 255, 255));
        btnedit1.setText("Edit");
        btnedit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnedit1ActionPerformed(evt);
            }
        });

        btnedit2.setBackground(new java.awt.Color(0, 0, 0));
        btnedit2.setForeground(new java.awt.Color(255, 255, 255));
        btnedit2.setText("Edit");
        btnedit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnedit2ActionPerformed(evt);
            }
        });

        lblCommunity2.setText("City");

        lblCommunity3.setText("City");

        lblCommunity4.setText("Community");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblCityid1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                                    .addComponent(txtCityid1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblCity1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btndelete)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnview)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnpop)
                                            .addComponent(btnedit)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCity)
                                    .addComponent(lblCityid))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCityid)
                                    .addComponent(txtCity)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btncreate, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(106, 106, 106)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCommunity1)
                            .addComponent(lblCommunityid1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCommunityid1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCommunity1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnedit1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCommunityid, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCommunity)
                            .addComponent(lblCommunity2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCommunityid)
                            .addComponent(txtCommunity)
                            .addComponent(ComboBoxCity, 0, 225, Short.MAX_VALUE)))
                    .addComponent(btncreate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btndelete1)
                        .addGap(18, 18, 18)
                        .addComponent(btnview1)
                        .addGap(18, 18, 18)
                        .addComponent(btnpop1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblHouseNo1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtHouseno1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblHouse1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtHouse1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btndelete2)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnview2)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnpop2)
                                    .addComponent(btnedit2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHouse)
                                    .addComponent(lblCommunity3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHouseNo)
                                    .addComponent(lblCommunity4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHouseno, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtHouse, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ComboBoxComm, javax.swing.GroupLayout.Alignment.TRAILING, 0, 225, Short.MAX_VALUE)
                                    .addComponent(ComboBoxCity1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btncreate1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(390, 390, 390))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btndelete, btnpop, btnview});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btndelete1, btnpop1, btnview1});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btndelete2, btnpop2, btnview2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCity)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCityid)
                            .addComponent(txtCityid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btncreate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboBoxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCommunity2))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCommunity))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCommunityid)
                                    .addComponent(txtCommunityid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboBoxCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCommunity3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboBoxComm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCommunity4))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHouse))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHouseno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHouseNo))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btncreate1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncreate2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnview)
                                    .addComponent(btnpop)
                                    .addComponent(btndelete)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnview1)
                                    .addComponent(btnpop1)
                                    .addComponent(btndelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCity1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCityid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCityid1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblCommunity1)
                                            .addComponent(txtCommunity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtCommunityid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCommunityid1)))
                                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndelete2)
                            .addComponent(btnview2)
                            .addComponent(btnpop2))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHouse1)
                            .addComponent(txtHouse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHouseNo1)
                            .addComponent(txtHouseno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnedit2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnedit1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ComboBoxCity, ComboBoxCity1, ComboBoxComm, txtCity, txtCityid, txtCommunity, txtCommunityid, txtHouse, txtHouseno});

    }// </editor-fold>//GEN-END:initComponents

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        // TODO add your handling code here:
        if(txtCity.getText().length() != 0 || txtCityid.getText().length() != 0)
        {        
            String City = txtCity.getText();
            int Cityid  = Integer.valueOf(txtCityid.getText());
            City newCity = mainSystem.addnewCity();

            if(mainSystem.checkCityid(Cityid)){
                JOptionPane.showMessageDialog(this,"The ID is already taken");
            }else{
                txtCity.setText("");
                txtCityid.setText("");

                newCity.setCityname(City);
                newCity.setCityId(Cityid);        
                popcity(); 
            }
           
        }else{
            JOptionPane.showMessageDialog(this, "Please Fill All The Fields");  
        }    

    }//GEN-LAST:event_btncreateActionPerformed

    private void btnpopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpopActionPerformed
        // TODO add your handling code here:
        popTable();

    }//GEN-LAST:event_btnpopActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:
        int SelectedRow = tblRecords.getSelectedRow();
        if(SelectedRow<0){
            JOptionPane.showMessageDialog(this, "Please Select a row");
        }else{
            DefaultTableModel m2 = (DefaultTableModel)tblRecords.getModel();
            //System.out.println(m2);
            //MainSystem a = new MainSystem();
            City SelectedRecords = (City) m2.getValueAt(SelectedRow, 0);
            //System.out.println("THIS IS THE SELECTED ROW"+SelectedRecords);        

            txtCity1.setText(SelectedRecords.getCityname());
            txtCityid1.setText(String.valueOf(SelectedRecords.getCityId()));
        }
    }//GEN-LAST:event_btnviewActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:

        boolean b1 = rolecheck();
        System.out.println("ONLY ADMIN CAN DO THIS " + b1);
        int SelectedRow = tblRecords.getSelectedRow();
        if(SelectedRow<0){
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }
        if(b1){
            DefaultTableModel m2 = (DefaultTableModel)tblRecords.getModel();
            City SelectedRecords = (City) m2.getValueAt(SelectedRow, 0);   
            mainSystem.deleteCity(SelectedRecords);        
            JOptionPane.showMessageDialog(this,"Selected row has been deleted");
            popTable();                  
        }
  
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
    int SelectedRow = tblRecords.getSelectedRow();
        if(SelectedRow<0){
            JOptionPane.showMessageDialog(this, "Please Select a row");
        }else{
            if(txtCity1.getText().length() != 0 || txtCityid1.getText().length() != 0 )
            {            
                DefaultTableModel m2 = (DefaultTableModel)tblRecords.getModel();
                City SelectedRecords = (City) m2.getValueAt(SelectedRow, 0);
                ArrayList<City> results = this.mainSystem.searchCity(SelectedRecords.getCityname());
                if(mainSystem.checkCityid(Integer.valueOf(txtCityid1.getText()))){
                    JOptionPane.showMessageDialog(this, "The input Id is already in use");
                }else{
                    results.get(0).setCityname(txtCity1.getText());
                    results.get(0).setCityId(Integer.valueOf(txtCityid1.getText()));                        
                    JOptionPane.showMessageDialog(this, "Data has been updated");                       
                }

            }else{
                JOptionPane.showMessageDialog(this, "Please Fill All The Fields");  
            }    
   
        }        
    }//GEN-LAST:event_btneditActionPerformed

    private void btncreate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreate1ActionPerformed
        // TODO add your handling code here:
        if(ComboBoxCity1.getSelectedItem().toString().length() ==0 ){
            JOptionPane.showMessageDialog(this, "Please Create a City");
        }else{
            if(txtHouse.getText().length() != 0 || txtHouseno.getText().length()!=0 || ComboBoxCity1.getSelectedItem().toString().length() != 0 || ComboBoxComm.getSelectedItem().toString().length() != 0 ){
                String Houseadd = txtHouse.getText();
                int Houseid = Integer.valueOf(txtHouseno.getText());
                //House hse = mainSystem.addnewCity().addCommunity().addNewHouse();

                for(City ct1 : mainSystem.getAllcities()){
                    for(Community com1 : ct1.getAllcommunities()){
                        if(com1.checkhouseid(Houseid)){
                            JOptionPane.showMessageDialog(this,"The input Id is already in use");
                        }else{
                            if(com1.getCommunityname().equals(ComboBoxComm.getSelectedItem().toString())){
                                Community comm = new Community();
                                House hse = com1.addNewHouse();
                                hse.setHouseno(Houseid);
                                hse.setAddress(Houseadd); 
                                comm.setCommunityname(ComboBoxComm.getSelectedItem().toString());
                                hse.setCommunity(comm);    
                                txtHouse.setText("");
                                txtHouseno.setText("");    
                                popcomm();
                                popcity1();                                   
                            }
                     
                        }

                    }
                }        


            }else{
                JOptionPane.showMessageDialog(this, "Please Fill All The Fields");  
            }            
        }

  
                
    }//GEN-LAST:event_btncreate1ActionPerformed

    private void btncreate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreate2ActionPerformed
        // TODO add your handling code here:
        if(txtCommunity.getText().length() != 0 || txtCommunityid.getText().length()!=0 || ComboBoxCity.getSelectedItem().toString().length() != 0 ) 
        {        
            
            
            
            String Comm = txtCommunity.getText();
            int Commid = Integer.valueOf(txtCommunityid.getText());
            //Community comm = mainSystem.addnewCity().addCommunity();
            for(City ct1 : mainSystem.getAllcities()){
                if(ct1.checkcommid(Commid)){
                    JOptionPane.showMessageDialog(this, "The Community Code is already in use");
                }else{
                    if(ct1.getCityname().equals(ComboBoxCity.getSelectedItem().toString())){
                        Community comm = ct1.addCommunity();
                        comm.setCommunityname(Comm);
                        comm.setZipcode(Commid);       
                        City ct = new City();
                        ct.setCityname(ComboBoxCity.getSelectedItem().toString());
                        comm.setCity(ct);             
                        txtCommunityid.setText("");   
                        txtCommunity.setText("");  
                        popcity();
                        popcomm();
                        popcity1();        
                    }
              
                }

            }


        }
        else{
            JOptionPane.showMessageDialog(this, "Please Fill All The Fields");
        }
        
           
    }//GEN-LAST:event_btncreate2ActionPerformed

    private void btnview1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnview1ActionPerformed
        // TODO add your handling code here:
        int SelectedRow = tblRecords2.getSelectedRow();
        if(SelectedRow<0){
            JOptionPane.showMessageDialog(this, "Please Select a row");
        }else{
            DefaultTableModel m2 = (DefaultTableModel)tblRecords2.getModel();
            //System.out.println(m2);
            //MainSystem a = new MainSystem();
            Community SelectedRecords = (Community) m2.getValueAt(SelectedRow, 0);
            //System.out.println("THIS IS THE SELECTED ROW"+SelectedRecords);        
            txtCommunity1.setText(SelectedRecords.getCommunityname());
            txtCommunityid1.setText(String.valueOf(SelectedRecords.getZipcode()));
            
        }        
    }//GEN-LAST:event_btnview1ActionPerformed

    private void btnpop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpop1ActionPerformed
        // TODO add your handling code here:
        popTable2();
    }//GEN-LAST:event_btnpop1ActionPerformed

    private void btndelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete1ActionPerformed
        // TODO add your handling code here:
        boolean b1 = rolecheck();
        System.out.println("ONLY ADMIN CAN DO THIS " + b1);
        int SelectedRow = tblRecords2.getSelectedRow();
        if(SelectedRow<0){
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }
        if(b1){
            DefaultTableModel m2 = (DefaultTableModel)tblRecords2.getModel();
            Community SelectedRecords = (Community) m2.getValueAt(SelectedRow, 0);   
            for(City ct1 : mainSystem.getAllcities()){
                ct1.deleteCommunity(SelectedRecords);
            }
            JOptionPane.showMessageDialog(this,"Selected row has been deleted");
            popTable2();                  
        }        
    }//GEN-LAST:event_btndelete1ActionPerformed

    private void btnpop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpop2ActionPerformed
        // TODO add your handling code here:
        popTable3();
    }//GEN-LAST:event_btnpop2ActionPerformed

    private void btndelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete2ActionPerformed
        // TODO add your handling code here:
        boolean b1 = rolecheck();
        System.out.println("ONLY ADMIN CAN DO THIS " + b1);
        int SelectedRow = tblRecords2.getSelectedRow();
        if(SelectedRow<0){
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }
        if(b1){
            DefaultTableModel m2 = (DefaultTableModel)tblRecords2.getModel();
            Community SelectedRecords = (Community) m2.getValueAt(SelectedRow, 0);   
            for(City ct1 : mainSystem.getAllcities()){
                for (Community ct2 : ct1.getAllcommunities()){
                    for(House ct3 : ct2.getAllhouses()){
                        if(ct2.getCommunityname().equals(ct3.getCommunity().getCommunityname())){
                         ct3.deleteHouse(ct3);                            
                        }

                        
                    }
                }
            }
            JOptionPane.showMessageDialog(this,"Selected row has been deleted");
            popTable3();                  
        }                
        
    }//GEN-LAST:event_btndelete2ActionPerformed

    private void btnview2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnview2ActionPerformed
        // TODO add your handling code here:
        int SelectedRow = tblRecords1.getSelectedRow();
        if(SelectedRow<0){
            JOptionPane.showMessageDialog(this, "Please Select a row");
        }else{
            DefaultTableModel m2 = (DefaultTableModel)tblRecords1.getModel();
            //System.out.println(m2);
            House SelectedRecords = (House) m2.getValueAt(SelectedRow, 0);
            //System.out.println("THIS IS THE SELECTED ROW"+SelectedRecords);        

            txtHouse1.setText(SelectedRecords.getAddress());
            txtHouseno1.setText(String.valueOf(SelectedRecords.getHouseno()));
        }        
        
    }//GEN-LAST:event_btnview2ActionPerformed

    private void btnedit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnedit1ActionPerformed
        // TODO add your handling code here:
    int SelectedRow = tblRecords2.getSelectedRow();
        if(SelectedRow<0){
            JOptionPane.showMessageDialog(this, "Please Select a row");
        }else{
            if(txtCommunity1.getText().length() != 0 || txtCommunityid1.getText().length() != 0)
            {            
            DefaultTableModel m2 = (DefaultTableModel)tblRecords2.getModel();
            Community SelectedRecords = (Community) m2.getValueAt(SelectedRow, 0);
            
            for(City ct1 : mainSystem.getAllcities()){
                if(ct1.checkcommid(Integer.valueOf(txtCommunityid1.getText()))){
                    JOptionPane.showMessageDialog(this, "The input Id is already in use");
                }else{
                    ArrayList<Community> searchComm = ct1.searchCommunity(SelectedRecords.getCommunityname());
                    System.out.println("Search Param "+ searchComm.size());
                    searchComm.get(0).setCommunityname(txtCommunity1.getText());
                    searchComm.get(0).setZipcode(Integer.valueOf(txtCommunityid1.getText()));                    
                }

            }            

//            SelectedRecords.getHse().setHouseno(Integer.valueOf(txtCityid1.getText()));                            
            JOptionPane.showMessageDialog(this, "Data has been updated");    
            
            }else{
            JOptionPane.showMessageDialog(this, "Please Fill All The Fields");    

            }
  
        }            
    }//GEN-LAST:event_btnedit1ActionPerformed

    private void btnedit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnedit2ActionPerformed
        // TODO add your handling code here:
    int SelectedRow = tblRecords1.getSelectedRow();
        if(SelectedRow<0){
            JOptionPane.showMessageDialog(this, "Please Select a row");
        }else{
            if(txtHouse1.getText().length() != 0 || txtHouseno1.getText().length() != 0){
            DefaultTableModel m2 = (DefaultTableModel)tblRecords1.getModel();
            //System.out.println(m2);
            House SelectedRecords = (House) m2.getValueAt(SelectedRow, 0);
            //ArrayList<House> searchHouse = new ArrayList();
            for(City ct1 : mainSystem.getAllcities()){
                for(Community cm :ct1.getAllcommunities()){
                    if(cm.getCommunityname().equals(SelectedRecords.getCommunity().getCommunityname())){
                        if(cm.checkhouseid(Integer.valueOf(txtHouseno1.getText()))){
                            JOptionPane.showMessageDialog(this, "The input Id is already in use");
                        }else{
                            ArrayList<House> searchHouse = cm.searchHouse(SelectedRecords.getAddress());
                            System.out.println("SIZE  "+ searchHouse.size());
                            searchHouse.get(0).setAddress(txtHouse1.getText());
                            Community cm1 = new Community();
                            cm1.setCommunityname(SelectedRecords.getCommunity().getCommunityname());
                            searchHouse.get(0).setCommunity(cm1);
                            searchHouse.get(0).setHouseno(Integer.valueOf(txtHouseno1.getText()));                             
                        }

                    }
                }        
            }            

//            SelectedRecords.getHse().setHouseno(Integer.valueOf(txtCityid1.getText()));                            
            JOptionPane.showMessageDialog(this, "Data has been updated");                      
                
            }else{
                JOptionPane.showMessageDialog(this, "Please Fill All The Fields");  
            }

        }                    
        
    }//GEN-LAST:event_btnedit2ActionPerformed

    private void txtCityidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityidKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }        
    }//GEN-LAST:event_txtCityidKeyTyped

    private void txtCommunityidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCommunityidKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }        
    }//GEN-LAST:event_txtCommunityidKeyTyped

    private void txtHousenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHousenoKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }        
    }//GEN-LAST:event_txtHousenoKeyTyped

    private void txtCityid1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityid1KeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }        
    }//GEN-LAST:event_txtCityid1KeyTyped

    private void txtCommunityid1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCommunityid1KeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }        
    }//GEN-LAST:event_txtCommunityid1KeyTyped

    private void txtHouseno1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHouseno1KeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }        
    }//GEN-LAST:event_txtHouseno1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxCity;
    private javax.swing.JComboBox<String> ComboBoxCity1;
    private javax.swing.JComboBox<String> ComboBoxComm;
    private javax.swing.JButton btncreate;
    private javax.swing.JButton btncreate1;
    private javax.swing.JButton btncreate2;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btndelete1;
    private javax.swing.JButton btndelete2;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnedit1;
    private javax.swing.JButton btnedit2;
    private javax.swing.JButton btnpop;
    private javax.swing.JButton btnpop1;
    private javax.swing.JButton btnpop2;
    private javax.swing.JButton btnview;
    private javax.swing.JButton btnview1;
    private javax.swing.JButton btnview2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCity1;
    private javax.swing.JLabel lblCityid;
    private javax.swing.JLabel lblCityid1;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblCommunity1;
    private javax.swing.JLabel lblCommunity2;
    private javax.swing.JLabel lblCommunity3;
    private javax.swing.JLabel lblCommunity4;
    private javax.swing.JLabel lblCommunityid;
    private javax.swing.JLabel lblCommunityid1;
    private javax.swing.JLabel lblHouse;
    private javax.swing.JLabel lblHouse1;
    private javax.swing.JLabel lblHouseNo;
    private javax.swing.JLabel lblHouseNo1;
    private javax.swing.JTable tblRecords;
    private javax.swing.JTable tblRecords1;
    private javax.swing.JTable tblRecords2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCity1;
    private javax.swing.JTextField txtCityid;
    private javax.swing.JTextField txtCityid1;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtCommunity1;
    private javax.swing.JTextField txtCommunityid;
    private javax.swing.JTextField txtCommunityid1;
    private javax.swing.JTextField txtHouse;
    private javax.swing.JTextField txtHouse1;
    private javax.swing.JTextField txtHouseno;
    private javax.swing.JTextField txtHouseno1;
    // End of variables declaration//GEN-END:variables

    private void popTable() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        tblRecords.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        DefaultTableModel m1 = (DefaultTableModel)tblRecords.getModel();
        m1.setRowCount(0);
        for(City Cs: this.mainSystem.getAllcities()){
           Object[] row = new Object[2];
           row[0] = Cs;
           row[1] = Cs.getCityId();
           m1.addRow(row);
        }
    }

    private void popTable2() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        tblRecords2.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        DefaultTableModel m1 = (DefaultTableModel)tblRecords2.getModel();
        m1.setRowCount(0);
        for(City Cs: this.mainSystem.getAllcities()){
            for(Community Cs1 :Cs.getAllcommunities()){
                Object[] row = new Object[3];
                row[0] = Cs1;
                row[1] = Cs1.getZipcode();
                row[2] = Cs1.getCity().getCityname();
                m1.addRow(row);
            }
        }
    }

    private void popTable3() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        tblRecords1.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        DefaultTableModel m1 = (DefaultTableModel)tblRecords1.getModel();
        m1.setRowCount(0);
        
        for(City Cs: this.mainSystem.getAllcities()){
            Object[] row = new Object[4];

            for(Community Cs1 :Cs.getAllcommunities()){
                for(House Cs2 :Cs1.getAllhouses()){
                    if(Cs1.getCommunityname().equals(Cs2.getCommunity().getCommunityname())){
                        System.out.println("MATCHHHHHHHHHHHHHHHH " + Cs1.getCommunityname());
                        row[0] = Cs2;
                        row[1] = Cs2.getHouseno();
                        row[2] = Cs2.getCommunity().getCommunityname();
                        row[3] = Cs.getCityname();
                        m1.addRow(row);                        
                    }

                }
    
            }

        }
    }    
    public void popcity(){
    ComboBoxCity.removeAllItems();
    ComboBoxCity.addItem("");    
    
    for(City ct : mainSystem.getAllcities()){
          ComboBoxCity.addItem(ct.getCityname());
          System.out.println("CITIES ARE "+ ct.getCityname());
    }      
    }  
    public void popcity1(){
        ComboBoxCity1.removeAllItems();
        ComboBoxCity1.addItem("");    

        for(City ct : mainSystem.getAllcities()){
              ComboBoxCity1.addItem(ct.getCityname());
              System.out.println("CITIES ARE "+ ct.getCityname());
        }   
    }
    public void popcity2(String city){
    ComboBoxCity.removeAllItems(); 
    ComboBoxCity.addItem(city);  
    for(City ct : mainSystem.getAllcities()){
          if(ct.getCityname().equals(city)){
              System.out.println("NO");
          }else{
            ComboBoxCity.addItem(ct.getCityname());
            System.out.println("CITIES ARE "+ ct.getCityname());              
          }

    }
    }
    
    public void popcomm(){  
    ComboBoxComm.removeAllItems();
    ComboBoxComm .addItem("");
    for(City ct : mainSystem.getAllcities()){
        for(Community ct2 : ct.getAllcommunities()){
            ComboBoxComm .addItem(ct2.getCommunityname());   
        }
      }      
    }

    
//    public MainSystem getcitydata(){
//        return city1;
//    }    
    
}

