/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import UI.SystemAdminJPanel;
import java.awt.Dimension;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.CredentialDirectory;
import model.Credentials;
import UI.MainJFrame;
import UI.CityAdminCreateJPanel;
import model.Crudops;
import UI.HospAdminCreateJPanel;
import model.City;
import UI.HospAdminCreateJPanel;
import javax.swing.JCheckBox;
import model.MainSystem;
/**
 *
 * @author abhis
 */
public class SystemAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminJPanel
     */
    Crudops crudops1;
    CredentialDirectory allcredentials;    
    City city1;
    MainSystem mainSystem;
    public SystemAdminJPanel(MainSystem mainSystem,CredentialDirectory allcredentials) {
        initComponents();
        this.allcredentials = allcredentials;        
        this.crudops1 = crudops1;
        this.mainSystem = mainSystem;
//        this.city1 = mainSystem.addnewCity();

    }
    private Boolean checkBlankInput()
    {
        if(txtuname.getText().length()==0 || txtpassword.getPassword().length ==0 || (chkbxHospAdmin.getText().length()==0 && chkbxPatient.getText().length()==0 && chkbxDoctor.getText().length()==0 && chkbxCommAdmin.getText().length()==0))
                
        {
            return false;  
        }
        else{
            return true;
        }
    }

    private boolean checkbox(){
        JCheckBox[] newList = new JCheckBox[4];
        newList[0] = chkbxCommAdmin;
        newList[1] = chkbxHospAdmin;
        newList[2] = chkbxDoctor;
        newList[3] = chkbxPatient;
        int k = 0;
        for (int i = 0; i < newList.length; i++) {
            if(newList[i].isSelected()){
                System.out.println(k);
                k+=1;
            }
        }
        if(k==1){
            return false;            
        }else{
            return true;
        }
}
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SplitPane = new javax.swing.JSplitPane();
        contorlPanel = new javax.swing.JPanel();
        contorlPanel1 = new javax.swing.JPanel();
        btnCity1 = new javax.swing.JButton();
        btnCitizen = new javax.swing.JButton();
        btnHospital = new javax.swing.JButton();
        btnDoctors = new javax.swing.JButton();
        Patients = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        Patients1 = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chkbxCommAdmin = new javax.swing.JCheckBox();
        chkbxHospAdmin = new javax.swing.JCheckBox();
        chkbxDoctor = new javax.swing.JCheckBox();
        chkbxPatient = new javax.swing.JCheckBox();
        brncreatecredentials = new javax.swing.JButton();

        contorlPanel1.setBackground(new java.awt.Color(0, 0, 0));
        contorlPanel1.setForeground(new java.awt.Color(204, 0, 51));

        btnCity1.setText("City");
        btnCity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCity1ActionPerformed(evt);
            }
        });

        btnCitizen.setText("Citizens");
        btnCitizen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitizenActionPerformed(evt);
            }
        });

        btnHospital.setText("Hospitals");
        btnHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalActionPerformed(evt);
            }
        });

        btnDoctors.setText("Doctors");
        btnDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorsActionPerformed(evt);
            }
        });

        Patients.setText("Patients");
        Patients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientsActionPerformed(evt);
            }
        });

        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        btnhome.setText("Home");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        Patients1.setText("View Doctors");
        Patients1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patients1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contorlPanel1Layout = new javax.swing.GroupLayout(contorlPanel1);
        contorlPanel1.setLayout(contorlPanel1Layout);
        contorlPanel1Layout.setHorizontalGroup(
            contorlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contorlPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contorlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlogout, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Patients1)
                    .addComponent(btnhome)
                    .addComponent(Patients)
                    .addComponent(btnCitizen)
                    .addComponent(btnHospital)
                    .addComponent(btnCity1)
                    .addComponent(btnDoctors))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        contorlPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Patients, Patients1, btnCitizen, btnCity1, btnDoctors, btnHospital, btnhome, btnlogout});

        contorlPanel1Layout.setVerticalGroup(
            contorlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contorlPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnhome)
                .addGap(18, 18, 18)
                .addComponent(btnCity1)
                .addGap(18, 18, 18)
                .addComponent(btnCitizen)
                .addGap(18, 18, 18)
                .addComponent(btnHospital)
                .addGap(18, 18, 18)
                .addComponent(btnDoctors)
                .addGap(18, 18, 18)
                .addComponent(Patients)
                .addGap(18, 18, 18)
                .addComponent(Patients1)
                .addGap(18, 18, 18)
                .addComponent(btnlogout)
                .addContainerGap(401, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contorlPanelLayout = new javax.swing.GroupLayout(contorlPanel);
        contorlPanel.setLayout(contorlPanelLayout);
        contorlPanelLayout.setHorizontalGroup(
            contorlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contorlPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(contorlPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        contorlPanelLayout.setVerticalGroup(
            contorlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contorlPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SplitPane.setLeftComponent(contorlPanel);

        workArea.setBackground(new java.awt.Color(51, 51, 51));
        workArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("System Admin Portal");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Create credentials for different person");

        txtuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunameActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pick role");

        chkbxCommAdmin.setForeground(new java.awt.Color(255, 255, 255));
        chkbxCommAdmin.setText("Community Admin");
        chkbxCommAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxCommAdminActionPerformed(evt);
            }
        });

        chkbxHospAdmin.setForeground(new java.awt.Color(255, 255, 255));
        chkbxHospAdmin.setText("Hospital Admin");
        chkbxHospAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxHospAdminActionPerformed(evt);
            }
        });

        chkbxDoctor.setForeground(new java.awt.Color(255, 255, 255));
        chkbxDoctor.setText("Doctor");
        chkbxDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxDoctorActionPerformed(evt);
            }
        });

        chkbxPatient.setForeground(new java.awt.Color(255, 255, 255));
        chkbxPatient.setText("Patient");
        chkbxPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxPatientActionPerformed(evt);
            }
        });

        brncreatecredentials.setText("Create Credentials");
        brncreatecredentials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brncreatecredentialsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(workAreaLayout.createSequentialGroup()
                        .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(57, 57, 57)
                        .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(workAreaLayout.createSequentialGroup()
                                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkbxCommAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkbxDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkbxPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkbxHospAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(brncreatecredentials, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtuname, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(workAreaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 355, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(211, 211, 211))))
        );

        workAreaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {chkbxCommAdmin, chkbxDoctor, chkbxHospAdmin, chkbxPatient});

        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(workAreaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2))
                    .addGroup(workAreaLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)))
                .addGap(54, 54, 54)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtuname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkbxCommAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkbxHospAdmin))
                .addGap(27, 27, 27)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkbxDoctor)
                    .addComponent(chkbxPatient))
                .addGap(43, 43, 43)
                .addComponent(brncreatecredentials, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(410, Short.MAX_VALUE))
        );

        workAreaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtpassword, txtuname});

        workAreaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {chkbxCommAdmin, chkbxDoctor, chkbxHospAdmin, chkbxPatient});

        SplitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCitizenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitizenActionPerformed
        // TODO add your handling code here:
        CitizenCreateJPanel cjp1 = new CitizenCreateJPanel(mainSystem,allcredentials);
        SplitPane.setRightComponent(cjp1);

    }//GEN-LAST:event_btnCitizenActionPerformed

    private void btnCity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCity1ActionPerformed
        // TODO add your handling code here:
        CityAdminCreateJPanel cjp = new CityAdminCreateJPanel(mainSystem,allcredentials);
        SplitPane.setRightComponent(cjp);
    }//GEN-LAST:event_btnCity1ActionPerformed

    private void btnHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalActionPerformed
        // TODO add your handling code here:
        HospAdminCreateJPanel hjp = new HospAdminCreateJPanel(mainSystem,allcredentials);
        SplitPane.setRightComponent(hjp);        
    }//GEN-LAST:event_btnHospitalActionPerformed

    private void btnDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorsActionPerformed
        // TODO add your handling code here:
        DoctorCreateJPanel djp = new DoctorCreateJPanel(mainSystem,allcredentials);
        SplitPane.setRightComponent(djp);
    }//GEN-LAST:event_btnDoctorsActionPerformed

    private void PatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientsActionPerformed
        // TODO add your handling code here:
        DoctorPatientCreateJPanel dpjp = new DoctorPatientCreateJPanel(mainSystem,allcredentials);
        SplitPane.setRightComponent(dpjp);
    }//GEN-LAST:event_PatientsActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        SystemAdminJPanel frame = new SystemAdminJPanel(mainSystem,allcredentials);
        Window w = SwingUtilities.getWindowAncestor(SystemAdminJPanel.this);
        w.setVisible(false);
        MainJFrame frame1 = new MainJFrame(mainSystem,allcredentials);
        frame1.setVisible(true);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void chkbxCommAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxCommAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkbxCommAdminActionPerformed

    private void chkbxHospAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxHospAdminActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_chkbxHospAdminActionPerformed

    private void chkbxDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkbxDoctorActionPerformed

    private void chkbxPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxPatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkbxPatientActionPerformed

    private void brncreatecredentialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brncreatecredentialsActionPerformed
        // TODO add your handling code here:
        Credentials cred1 = allcredentials.addNewCredentials();
        String uname = txtuname.getText();
        String pass = String.valueOf(txtpassword.getPassword());
        if(uname.equals("") || pass.equals("")){
            JOptionPane.showMessageDialog(this, "Please fill the fields");
        }else if(checkbox()){
            JOptionPane.showMessageDialog(this, "Please fill only a single role");
            
        }
        else{
            if(chkbxPatient.isSelected()){
                String role = chkbxPatient.getText();                              
                chkbxPatient.setSelected(false);
                cred1.setPassword(pass);
                cred1.setRole(role);
                cred1.setUsername(uname);
            }
            else if(chkbxCommAdmin.isSelected()){
                String role = chkbxCommAdmin.getText();
                chkbxCommAdmin.setSelected(false);    
                cred1.setPassword(pass);
                cred1.setRole(role);
                cred1.setUsername(uname);         
            }
            else if(chkbxDoctor.isSelected()){
                String role = chkbxDoctor.getText();    
                chkbxDoctor.setSelected(false);       
                cred1.setPassword(pass);
                cred1.setRole(role);
                cred1.setUsername(uname);               

            }
            else if(chkbxHospAdmin.isSelected()){
                String role = chkbxHospAdmin.getText();   
                chkbxHospAdmin.setSelected(false);
                cred1.setPassword(pass);
                cred1.setRole(role);
                cred1.setUsername(uname);      

            }else{
                JOptionPane.showMessageDialog(this,"Please Input a Role");
                String role = "";
            }     
            
            JOptionPane.showMessageDialog(this, "Credentials Created for user");
        }
        System.out.println("HEY MAN THIS IS YOUR CREDENTIAL ADDED " +allcredentials.getCredential().get(0).getRole());
  
    }//GEN-LAST:event_brncreatecredentialsActionPerformed

    private void txtunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunameActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // TODO add your handling code here:
        SplitPane.setRightComponent(workArea);
    }//GEN-LAST:event_btnhomeActionPerformed

    private void Patients1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patients1ActionPerformed
        // TODO add your handling code here:
        
        PatientCreateJPanel pjp = new PatientCreateJPanel(mainSystem,allcredentials);
        SplitPane.setRightComponent(pjp);
        
    }//GEN-LAST:event_Patients1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Patients;
    private javax.swing.JButton Patients1;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton brncreatecredentials;
    private javax.swing.JButton btnCitizen;
    private javax.swing.JButton btnCity1;
    private javax.swing.JButton btnDoctors;
    private javax.swing.JButton btnHospital;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnlogout;
    private javax.swing.JCheckBox chkbxCommAdmin;
    private javax.swing.JCheckBox chkbxDoctor;
    private javax.swing.JCheckBox chkbxHospAdmin;
    private javax.swing.JCheckBox chkbxPatient;
    private javax.swing.JPanel contorlPanel;
    private javax.swing.JPanel contorlPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtuname;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables

}
